Bumped json-path version to 2.4.0 to solve dependency issue (#32)
* Updated json-path to 2.4.0

* Updated pom parent to 2.35 due to JENKINS-45245

* Fixed NoClassDefFoundErrors in tests

* Parent pom version to 3.2